# Buổi 02 – Phân tích dữ liệu bán hàng (Sales Data Sample)

**Bộ dữ liệu:** `sales_data_sample.xlsx` – dữ liệu bán hàng của công ty đa quốc gia ABC.

**Mô tả các cột:**
| Cột | Ý nghĩa |
|---|---|
| ORDERNUMBER | Mã hóa đơn |
| QUANTITYORDERED | Số lượng sản phẩm đặt hàng |
| ORDERLINENUMBER | Dòng thông tin mua sản phẩm trên hóa đơn |
| SALES | Giá trị đặt hàng |
| ORDERDATE | Ngày đặt hàng |
| STATUS | Trạng thái giao hàng |
| COUNTRY | Địa điểm đặt hàng |
| DEALSIZE | Phân loại kích thước đơn hàng (Small/Medium/Large) |
| Discount | Giảm giá (%) |
| Profit | Lợi nhuận |

---
## Phần 1: Nhập và khám phá dữ liệu tổng quan

**Câu 1.** Đọc dữ liệu từ file `sales_data_sample.xlsx` vào DataFrame tên `df`. Hiển thị 5 dòng đầu và 5 dòng cuối của dữ liệu.

In [ ]:
import pandas as pd
df= pd.read_excel("sales_data_sample.xlsx") #doc file excel
df.head(5) #5 dong dau (nếu ko để số vào sẽ mặc định là 5)
df.tail(5) #5 dong cuoi

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.0,315.7404
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.2,2.3520
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.2,7.4694
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.2,22.6782
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.2,0.5580

In [ ]:
#overloading (nạp chồng hàm)
def ten_Ham(a,b): #nhận 2 tham số
    pass #tạm thời chưa làm gì, chỉ để báo lỗi

In [2]:
def ten_Ham(a,b,c):
    pass

**Câu 2.** Cho biết DataFrame có bao nhiêu dòng, bao nhiêu cột? Kiểu dữ liệu (dtype) của từng cột là gì?

In [7]:
df.shape #để biết bn dòng, bn cột

(2823, 10)

In [ ]:
print("Số dòng:", len(df))
print(f"Số dòng:", {len(df)}) #f để truyền gtri vào trong 1 cột

Số dòng: 2823
Số dòng: {2823}

In [3]:
df.columns #trả về cột
df.columns.tolist() #trả về 1 ds

['ORDERNUMBER',
 'QUANTITYORDERED',
 'ORDERLINENUMBER',
 'SALES',
 'ORDERDATE',
 'STATUS',
 'COUNTRY',
 'DEALSIZE',
 'Discount',
 'Profit']

In [4]:
for i in df.columns.tolist():
    print(i)

ORDERNUMBER
QUANTITYORDERED
ORDERLINENUMBER
SALES
ORDERDATE
STATUS
COUNTRY
DEALSIZE
Discount
Profit

In [ ]:
#kết lại và cách nhau bằng dấu phẩy
",".join(df.columns.tolist())

'ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit'

In [8]:
df.dtypes #kiểu dữ liệu của từng cột

ORDERNUMBER                 int64
QUANTITYORDERED             int64
ORDERLINENUMBER             int64
SALES                     float64
ORDERDATE          datetime64[us]
STATUS                        str
COUNTRY                       str
DEALSIZE                      str
Discount                  float64
Profit                    float64
dtype: object

In [ ]:
df.info() #cho biết cột, số lượng, gtri...

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ORDERNUMBER      2823 non-null   int64
 1   QUANTITYORDERED  2823 non-null   int64
 2   ORDERLINENUMBER  2823 non-null   int64
 3   SALES            2823 non-null   float64
 4   ORDERDATE        2823 non-null   datetime64[us]
 5   STATUS           2823 non-null   str
 6   COUNTRY          2823 non-null   str
 7   DEALSIZE         2823 non-null   str
 8   Discount         2823 non-null   float64
 9   Profit           2823 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(3), str(3)
memory usage: 220.7 KB

**Câu 3.** Kiểm tra xem dữ liệu có giá trị thiếu (missing values) ở cột nào không? Có dòng nào bị trùng lặp hoàn toàn (duplicate) không?

In [ ]:
df.isnull().sum #kt gtri thiếu
#df.isnull(): kt từng ô có bị thiếu ko, có bị null hay ko
#sum(): đếm số ô bị thiếu trong từng cột

<bound method DataFrame.sum of       ORDERNUMBER  QUANTITYORDERED  ORDERLINENUMBER  SALES  ORDERDATE  STATUS  \
0           False            False            False  False      False   False
1           False            False            False  False      False   False
2           False            False            False  False      False   False
3           False            False            False  False      False   False
4           False            False            False  False      False   False
...           ...              ...              ...    ...        ...     ...
2818        False            False            False  False      False   False
2819        False            False            False  False      False   False
2820        False            False            False  False      False   False
2821        False            False            False  False      False   False
2822        False            False            False  False      False   False

      COUNTRY  DEALSIZE  Discount  Profit
0       False     False     False   False
1       False     False     False   False
2       False     False     False   False
3       False     False     False   False
4       False     False     False   False
...       ...       ...       ...     ...
2818    False     False     False   False
2819    False     False     False   False
2820    False     False     False   False
2821    False     False     False   False
2822    False     False     False   False

[2823 rows x 10 columns]>

In [10]:
df.duplicated().sum #kt dòng bị trùng hoàn toàn
#df.duplicated(): kt mỗi dòng có trùng hoàn toàn với 1 dòng trước đó ko
#sum(): đếm tổng số dòng bị trùng

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
2818    False
2819    False
2820    False
2821    False
2822    False
Length: 2823, dtype: bool>

**Câu 4.** Sử dụng `describe()` để xem thống kê mô tả (min, max, mean, std...) cho các cột số: `QUANTITYORDERED`, `SALES`, `Discount`, `Profit`. Nhận xét ngắn gọn về khoảng giá trị của `Discount` và `Profit`.

In [ ]:
df[['QUANTITYORDERED', 'SALES', 'Discount', 'Profit']].describe()
# Nhận xét:
#Discount: min = 0, max = 0.8
#Profit: min = -3839.99, max = 3919.99

       QUANTITYORDERED         SALES     Discount       Profit
count      2823.000000   2823.000000  2823.000000  2823.000000
mean         35.092809   3553.889072     0.152710    25.383894
std           9.741443   1841.865106     0.203333   192.452771
min           6.000000    482.130000     0.000000 -3839.990400
25%          27.000000   2203.430000     0.000000     1.801600
50%          35.000000   3184.800000     0.150000     8.880000
75%          43.000000   4508.000000     0.200000    30.488300
max          97.000000  14082.800000     0.800000  3919.988800

**Câu 5.** Dữ liệu có bao nhiêu quốc gia (COUNTRY) khác nhau? Liệt kê tên các quốc gia đó. Có bao nhiêu giá trị khác nhau trong cột `STATUS` và `DEALSIZE`? Đó là những giá trị nào?

In [ ]:
#COUNTRY
df['COUNTRY'].unique() #tên các quốc gia ko trùng nhau

<StringArray>
[        'USA',      'France',      'Norway',   'Australia',     'Finland',
     'Austria',          'UK',       'Spain',      'Sweden',   'Singapore',
      'Canada',       'Japan',       'Italy',     'Denmark',     'Belgium',
 'Philippines',     'Germany', 'Switzerland',     'Ireland']
Length: 19, dtype: str

In [12]:
df['COUNTRY'].nunique() #nếu hỏi có bn quốc gia, hiện ds ra

#unique(): liệt kê các gtri khác nhau
#nunique(): đếm có bn gtri khác nhau

19

In [ ]:
df['COUNTRY'].value_counts() #đếm gtri xem xuất hiện bn lần, đếm gtri định danh

COUNTRY
USA            1004
Spain           342
France          314
Australia       185
UK              144
Italy           113
Finland          92
Norway           85
Singapore        79
Canada           70
Denmark          63
Germany          62
Sweden           57
Austria          55
Japan            52
Belgium          33
Switzerland      31
Philippines      26
Ireland          16
Name: count, dtype: int64

In [ ]:
#STATUS
df['STATUS'].unique()
df['STATUS'].nunique()

In [ ]:
#DEALSIZE
df['DEALSIZE'].unique()
df['DEALSIZE'].nunique()

In [11]:
df[['COUNTRY','STATUS','DEALSIZE']]

      COUNTRY    STATUS DEALSIZE
0         USA   Shipped    Small
1      France   Shipped    Small
2      France   Shipped   Medium
3         USA   Shipped   Medium
4         USA   Shipped   Medium
...       ...       ...      ...
2818    Spain   Shipped    Small
2819  Finland   Shipped   Medium
2820    Spain  Resolved   Medium
2821   France   Shipped    Small
2822      USA   On Hold   Medium

[2823 rows x 3 columns]

---
## Phần 2: Lọc và sắp xếp dữ liệu

**Câu 6.** Lọc ra các đơn hàng có `SALES` lớn hơn 5000. Có bao nhiêu đơn hàng thỏa điều kiện này?

In [ ]:
df[df['SALES']>5000] #SALES lớn hơn 5000
#df đầu tiên là kiếm df
#df thứ 2 là đi sâu dô

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.2,2.5164
7,10188,48,1,5512.32,2003-11-18,Shipped,Norway,Medium,0.2,90.7152
20,10341,41,9,7737.93,2004-11-24,Shipped,Austria,Large,0.2,7.3840
25,10417,66,2,7516.08,2005-05-13,Disputed,Spain,Large,0.2,4.2224
26,10103,26,11,5404.62,2003-01-29,Shipped,Norway,Medium,0.0,11.7741
...,...,...,...,...,...,...,...,...,...,...
2685,10361,44,10,5001.92,2004-12-17,Shipped,Australia,Medium,0.2,29.9850
2686,10375,44,11,5208.72,2005-02-03,Shipped,France,Medium,0.7,-2.4564
2689,10401,77,9,7084.00,2005-04-03,On Hold,USA,Large,0.2,1.6400
2715,10397,48,3,5192.64,2005-03-28,Shipped,France,Medium,0.0,62.3904
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.2,7.4694

In [14]:
#5000<SALES<8000
df[df['SALES']>5000 & (df['SALES']<8000)]

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580

In [ ]:
df[df['SALES']>5000 & (df['COUNTRY'] == "USA")]
#2 đk trở lên bỏ vào ngoặc tròn -> vuông

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
0,10107,30,2,2871.00,2003-02-24,Shipped,USA,Small,0.00,41.9136
1,10121,34,5,2765.90,2003-05-07,Shipped,France,Small,0.00,219.5820
2,10134,41,2,3884.34,2003-07-01,Shipped,France,Medium,0.00,6.8714
3,10145,45,6,3746.70,2003-08-25,Shipped,USA,Medium,0.45,-383.0310
4,10159,49,14,5205.27,2003-10-10,Shipped,USA,Medium,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,15,2244.40,2004-12-02,Shipped,Spain,Small,0.00,315.7404
2819,10373,29,1,3978.51,2005-01-31,Shipped,Finland,Medium,0.20,2.3520
2820,10386,43,4,5417.57,2005-03-01,Resolved,Spain,Medium,0.20,7.4694
2821,10397,34,1,2116.16,2005-03-28,Shipped,France,Small,0.20,22.6782
2822,10414,47,9,3079.44,2005-05-06,On Hold,USA,Medium,0.20,0.5580

In [20]:
#có bn đơn thỏa SALES > 5000
df[df['SALES'] > 5000].shape[0]

549

**Câu 7.** Lọc ra các đơn hàng thuộc quốc gia `USA` và có `DEALSIZE` là `Large`. Sắp xếp kết quả theo `SALES` giảm dần và hiển thị 10 dòng đầu tiên.

In [22]:
result = df[
    (df['COUNTRY'] == 'USA') #dòng có quốc gia là USA
            & (df['DEALSIZE'] == 'Large') #dòng có kích thước đơn hàng là Large
            ]

#sắp xếp dữ liệu dựa vào cột SALES
result = result.sort_values('SALES', ascending=False)
#ascending=False: giảm dần
#ascending=True: tăng dần

result.head(10) #lấy 10 dòng đầu sau khi đã sắp xếp

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,COUNTRY,DEALSIZE,Discount,Profit
598,10407,76,2,14082.80,2005-04-22,On Hold,USA,Large,0.2,1.0178
744,10322,50,6,12536.50,2004-11-04,Shipped,USA,Large,0.2,1.6762
44,10312,48,3,11623.70,2004-10-21,Shipped,USA,Large,0.0,19.7714
1133,10333,46,2,11336.70,2004-11-18,Shipped,USA,Large,0.2,-23.3640
188,10127,46,2,11279.20,2003-06-03,Shipped,USA,Large,0.2,6.2550
2505,10388,46,2,10066.60,2005-03-03,Shipped,USA,Large,0.0,327.5060
131,10400,64,9,9661.44,2005-04-01,Shipped,USA,Large,0.2,29.3640
175,10276,50,3,9631.00,2004-08-02,Shipped,USA,Large,0.2,6.5520
319,10142,46,11,9470.94,2003-08-08,Shipped,USA,Large,0.0,80.0226
164,10147,48,7,9245.76,2003-09-05,Shipped,USA,Large,0.2,2.7324

**Câu 8.** Lọc ra các đơn hàng có `Profit` âm (lỗ). Các đơn hàng này thường rơi vào `STATUS` nào? `DEALSIZE` nào? (Gợi ý: dùng `value_counts()`)

In [16]:
df_Profit = df[df['Profit'] < 0] #lọc các đơn Profit < 0
df_Profit[['STATUS', 'DEALSIZE']].value_counts()

STATUS      DEALSIZE
Shipped     Medium      220
            Small       205
            Large        29
Cancelled   Small         8
In Process  Small         7
            Medium        6
Cancelled   Medium        6
Resolved    Medium        6
On Hold     Small         5
            Medium        3
            Large         2
Disputed    Small         2
            Large         1
In Process  Large         1
Resolved    Small         1
Name: count, dtype: int64

In [ ]:
#lưu các dòng bị lỗ vào DataFrame mới, tên là loss
loss = df[df['Profit'] < 0]

#xem STATUS, DEALSIZE nào xuất hiện nhiều
loss['STATUS'].value_counts()
loss['DEALSIZE'].value_counts()
#loss['STATUS']: lấy riêng cột STATUS của các đơn hàng bị lỗ
#value_counts(): đếm mỗi gtri xuất hiện bn lần

DEALSIZE
Medium    241
Small     228
Large      33
Name: count, dtype: int64

**Câu 9.** Lọc ra các đơn hàng có mức giảm giá (`Discount`) từ 0.3 trở lên. Doanh số (`SALES`) trung bình của nhóm này là bao nhiêu, so với doanh số trung bình toàn bộ dữ liệu?

In [25]:
#lọc Discount >= 0.3 rồi lưu kq vào discount_high
discount_high = df[df['Discount'] >= 0.3]

In [26]:
#tính SALES trung bình của nhóm này
discount_high['SALES'].mean()
#.mean(): tính giá trị trung bình

np.float64(3590.8555091383814)

In [27]:
#tính SALES trung bình của toàn bộ dữ liệu
df['SALES'].mean()

np.float64(3553.889071909316)

---
## Phần 3: Tạo cột mới và biến đổi dữ liệu

**Câu 10.** Từ cột `ORDERDATE`, tạo thêm 3 cột mới: `ORDER_YEAR`, `ORDER_MONTH`, `ORDER_QUARTER` chứa năm, tháng, quý của ngày đặt hàng.

In [ ]:
#đảm bảo ORDERDATE là kiểu ngày
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])
#df['ORDERDATE'] có thể thay bằng df.ORDERDATE
#pd.to_datetime(): dùng để chuyển dữ liệu sang kiểu ngày tháng mà Pandas có thể xử lý

In [ ]:
df.ORDERDATE.dt.year #lấy ngày tháng năm, đặc thù của ngày tháng năm phải có .dt

In [ ]:
#lấy năm
df['ORDER_YEAR'] = df['ORDERDATE'].dt.year # hoặc df['ORDER_YEAR'] = df.ORDERDATE.dt.year (cái này dễ nhìn hơn)
#.dt: cho phép lấy các thành phần của ngày tháng
#.year: lấy năm

In [ ]:
#lấy tháng
df['ORDER_MONTH'] = df['ORDERDATE'].dt.month
#.month: lấy tháng

In [ ]:
#lấy quý
df['ORDER_QUARTER'] = df['ORDERDATE'].dt.quarter
#.quarter: lấy quý

**Câu 11.** Tạo cột mới `PROFIT_MARGIN` = `Profit` / `SALES` (tỷ suất lợi nhuận). Đơn hàng nào có tỷ suất lợi nhuận cao nhất? Thấp nhất?

In [ ]:
#tạo cột tỷ suất lợi nhuận
df['PROFIT_MARGIN'] = df['Profit'] / df['SALES']
#nếu muốn hiển thị dạng % thì *100

In [ ]:
#tìm đơn có tỷ suất CAO nhất
df.loc[df['PROFIT_MARGIN'].idxmax()]
#idxmax(): tìm vị trí/index có giá trị lớn nhất
#loc[...]: lấy toàn bộ dòng ở vị trí đó

In [ ]:
#tìm đơn có tỷ suất THẤP nhất
df.loc[df['PROFIT_MARGIN'].idxmin()]
#idxmin(): tìm vị trí có giá trị nhỏ nhất

In [ ]:
#nếu chỉ muốn biết giá trị cao nhất/thấp nhất
df['PROFIT_MARGIN'].max()
df['PROFIT_MARGIN'].min()

**Câu 12.** Tạo cột `NET_SALES` = `SALES` * (1 - `Discount`) thể hiện doanh số sau khi trừ giảm giá. So sánh tổng `SALES` và tổng `NET_SALES` của toàn bộ dữ liệu.

---
## Phần 4: Nhóm dữ liệu (Groupby) và tổng hợp

**Câu 13.** Tính tổng `SALES` và tổng `Profit` theo từng `COUNTRY`. Sắp xếp giảm dần theo tổng `SALES` và cho biết Top 5 quốc gia có doanh số cao nhất.

In [ ]:
df.groupby(by='COUNTRY')['SALES'].sum() #by là bởi cái gì
#hoặc df.groupby('COUNTRY')['SALES'].sum() #có thể bỏ by đi

COUNTRY
Australia       630623.10
Austria         202062.53
Belgium         108412.62
Canada          224078.56
Denmark         245637.15
Finland         329581.91
France         1110916.52
Germany         220472.09
Ireland          57756.43
Italy           374674.31
Japan           188167.81
Norway          307463.70
Philippines      94015.73
Singapore       288488.41
Spain          1215686.92
Sweden          210014.21
Switzerland     117713.56
UK              478880.46
USA            3627982.83
Name: SALES, dtype: float64

In [19]:
df.groupby(by='COUNTRY')[['SALES','Profit']].sum()

                  SALES      Profit
COUNTRY
Australia     630623.10   8113.6187
Austria       202062.53    655.5536
Belgium       108412.62   1143.8593
Canada        224078.56   5822.9162
Denmark       245637.15   2008.7175
Finland       329581.91   -378.7674
France       1110916.52   2940.2749
Germany       220472.09   1677.1145
Ireland        57756.43    486.0154
Italy         374674.31   4409.6194
Japan         188167.81    478.3726
Norway        307463.70   3015.3555
Philippines    94015.73     -8.5433
Singapore     288488.41   1887.8876
Spain        1215686.92  11779.8851
Sweden        210014.21    973.4532
Switzerland   117713.56    716.5745
UK            478880.46   4594.8300
USA          3627982.83  21341.9950

**Câu 14.** Tính `SALES` trung bình và `Profit` trung bình theo từng nhóm `DEALSIZE`. Nhận xét: nhóm `Large` có thực sự mang lại lợi nhuận trung bình cao nhất không?

**Câu 15.** Tính số lượng đơn hàng (đếm số `ORDERNUMBER` duy nhất) theo từng `STATUS`. Tỷ lệ đơn hàng bị `Cancelled` hoặc `Disputed` chiếm bao nhiêu % tổng số đơn hàng?

**Câu 16.** Sử dụng `pivot_table` để tạo bảng tổng hợp tổng `SALES` theo `COUNTRY` (hàng) và `DEALSIZE` (cột).

**Câu 17.** Theo `ORDER_YEAR` đã tạo ở Câu 10, tính tổng doanh số (`SALES`) theo từng năm. Doanh số năm nào cao nhất? Lưu ý gì về dữ liệu năm 2005 (dữ liệu có đủ 12 tháng không)?

---
## Phần 6: Câu hỏi tổng hợp / thảo luận

**Câu 22.** Từ những phân tích trên, hãy viết một đoạn nhận xét ngắn (5–7 dòng) về:
- Quốc gia nào đang mang lại doanh số/lợi nhuận tốt nhất cho công ty ABC?
- Nhóm `DEALSIZE` nào hiệu quả nhất?
- Có rủi ro nào đáng lưu ý (ví dụ: đơn hàng lỗ, tỷ lệ hủy/tranh chấp cao) không?
- Đề xuất 1–2 hành động công ty nên cân nhắc.